# Generated by Django 4.0.5 on 2022-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_feed_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='datetime_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
