# Generated by Django 4.0.5 on 2022-08-02 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('News_feed_view', '0004_subscribers_category_subscribed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_feed_view.category'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
